### ISSUE TITLE
Atualização para Manter Conformidade com o Always Free

### ISSUE THREAD

**Issue by Rapha-Borges** [Rapha-Borges/oke-free#8]
Devido à utilização inicial das instâncias "VM.Standard.E3.Flex" para o laboratório, que são instâncias pagas, e só conseguimos acesso gratuito graças ao apoio da Oracle Cloud, estamos atualizando o cluster para utilizar as instâncias Always Free "VM.Standard.A1.Flex".

Se você possuir créditos e quiser continuar utilizando as instâncias "VM.Standard.E3.Flex", não há problema algum. No entanto, lembre-se de migrar antes do término dos créditos para evitar qualquer cobrança.

Além disso, nos próximos dias, planejamos migrar o cluster de OKE para um cluster não gerenciado. Essa mudança proporcionará maior liberdade e nos permitirá explorar mais ferramentas de estudo, mantendo a conformidade com a proposta do Always Free.

Todo o processo de migração estará disponível neste repositório e será feito da forma mais simples possível.

# Nova branch para testes do cluster always-free

Criei a branch [always-free](https://github.com/Rapha-Borges/oke-free/tree/always-free) para testar o cluster utilizando apenas recursos gratuitos. No entanto, para realizar esse procedimento, você possivelmente precisará fazer o upgrade da conta para Pay As You Go para ter acesso à maior disponibilidade das instâncias VM.Standard.A1.Flex (único shape Always Free compatível com o OKE).

Fique atento ao utilizar o cluster dessa forma, pois outros recursos, não inclusos no Always Free, podem ser criados dependendo de como você utiliza a sua conta.

Por se tratar de um projeto colaborativo, mesmo que revisado por mim, não me responsabilizo por custos gerados devido à utilização desse laboratório. Sempre crie um alerta de custos no valor de R$ 1,00 para não ter surpresas.

![Screenshot from 2024-01-23 00-26-01](https://github.com/Rapha-Borges/oke-free/assets/53947674/3f0e5a71-0f98-44a1-8fed-487d83623862)

![Screenshot from 2024-01-23 00-24-36](https://github.com/Rapha-Borges/oke-free/assets/53947674/dbd0f291-6dbe-45b4-bb6f-5c6abcfe5ea4)

![photo_2024-01-23_00-31-08](https://github.com/Rapha-Borges/oke-free/assets/53947674/bfd225e8-b5b2-4172-b5e4-74ad4e59053e)

**Comment by faelp22** [comment]
@Rapha-Borges muito obrigado por isso, essa sua iniciativa vai estar ajudando muitas pessoas a aprender mais sobre Nuvem, Terraform e K8s vlw mesmo

**Comment by omurilo** [comment]
Uma dúvida, o problema que ocorre com o `A1.Flex` como vou deixar abaixo, é causado por falta de capacidade da região de receber o cluster? (nunca consegui usar aqueles cluster arm da ultima vez que foi disponibilizado porque nunca conseguia fazer o deploy, sempre o mesmo erro.)

```bash
Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.iad.aaaaaaaa73m2h7shrqtzubvwuvijbcwoyrxvdigkonkkolngvwtw3ofvjroa, entity: nodepool, action: CREATED. Message: 3 node(s) launch failure. Reason for failure on one of the nodes : Error returned by Unknown operation operation in Unknown service service.(500, InternalError, false) Out of host capacity
```

PS: O shape `Standard.E2.1.Micro` também não funciona, à pesar dele ser classificado como always free.

**Comment by ricardoklein** [comment]
Tá rolando agora (criei o cluster faz uns 30 minutos) com:
shape "VM.Standard.E3.Flex"
image_id "ocid1.image.oc1.iad.aaaaaaaanwsto6tqklfuawgqrve5ugjpbff3l5qtb7bs35dp72ewcnsuwoka"
k8s_version "v1.28.2"

**Comment by Rapha-Borges** [comment]
> Uma dúvida, o problema que ocorre com o `A1.Flex` como vou deixar abaixo, é causado por falta de capacidade da região de receber o cluster? (nunca consegui usar aqueles cluster arm da ultima vez que foi disponibilizado porque nunca conseguia fazer o deploy, sempre o mesmo erro.)
> 
> ```shell
> Error Message: work request did not succeed, workId: ocid1.clustersworkrequest.oc1.iad.aaaaaaaa73m2h7shrqtzubvwuvijbcwoyrxvdigkonkkolngvwtw3ofvjroa, entity: nodepool, action: CREATED. Message: 3 node(s) launch failure. Reason for failure on one of the nodes : Error returned by Unknown operation operation in Unknown service service.(500, InternalError, false) Out of host capacity
> ```
> 

Adicionei mais informações referentes ao erro 'Out of Capacity' nos [Problemas conhecidos](https://github.com/Rapha-Borges/oke-free#se-voc%C3%AA-tentar-criar-um-cluster-com-uma-conta-gratuita-e-receber-o-erro-abaixo). Em breve, teremos algumas atualizações relacionadas ao aumento da disponibilidade de instâncias. No entanto, se você criou a conta durante o #MêsDoKubernetes e possui os créditos oferecidos pela Oracle, pode utilizar o shape `VM.Standard.E3.Flex`, alterando todas as [Variáveis do Terraform personalizadas para o lab](https://github.com/Rapha-Borges/oke-free#vari%C3%A1veis-do-terraform-personalizadas-para-o-lab).

> PS: O shape `Standard.E2.1.Micro` também não funciona, à pesar dele ser classificado como always free.

O shape `Standard.E2.1.Micro`, apesar de possuir a tag Always Free, não é compatível com o cluster gerenciado da Oracle (OKE).

**Comment by fabiosleal2712** [comment]
> Tá rolando agora (criei o cluster faz uns 30 minutos) com: shape "VM.Standard.E3.Flex" image_id "ocid1.image.oc1.iad.aaaaaaaanwsto6tqklfuawgqrve5ugjpbff3l5qtb7bs35dp72ewcnsuwoka" k8s_version "v1.28.2"

Funcionou aqui pra mim

**Comment by flowramps** [comment]
@Rapha-Borges, vi que havia um sync no meu fork, os devidos ajustes para utilizar 100% free foram publicados de fato? Ou ainda está em processo de ajustes ?

Desde Já, agradeço.

**Comment by Rapha-Borges** [comment]
> @Rapha-Borges, vi que havia um sync no meu fork, os devidos ajustes para utilizar 100% free foram publicados de fato? Ou ainda está em processo de ajustes ?
> 
> Desde Já, agradeço.

Até agora, apenas foram realizadas correções para os problemas relatados pela comunidade. Assim que migrarmos para o cluster 100% free, informarei por meio deste canal. Recomendo ativar as notificações para esta Issue.

**Comment by rturatti** [comment]
Show, aqui com o shape "VM.Standard.E3.Flex", já está rolando.

Assim que atualizar para o Always Free, atualizo aqui para testar.

**Comment by victooooor** [comment]
> Devido à utilização inicial das instâncias "VM.Standard.E3.Flex" para o laboratório, que são instâncias pagas, e só conseguimos acesso gratuito graças ao apoio da Oracle Cloud, estamos atualizando o cluster para utilizar as instâncias Always Free "VM.Standard.A1.Flex".
> 
> Se você possuir créditos e quiser continuar utilizando as instâncias "VM.Standard.E3.Flex", não há problema algum. No entanto, lembre-se de migrar antes do término dos créditos para evitar qualquer cobrança.
> 
> Além disso, nos próximos dias, planejamos migrar o cluster de OKE para um cluster não gerenciado. Essa mudança proporcionará maior liberdade e nos permitirá explorar mais ferramentas de estudo, mantendo a conformidade com a proposta do Always Free.
> 
> Todo o processo de migração estará disponível neste repositório e será feito da forma mais simples possível.

Salve Rafa, acabei de clonar o repo, o terraform ta reclamando:
**Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded.**
│ Suggestion: Request a service limit increase for this resource Containerengine Cluster

Não é problema com seu código,  tentei subir manualmente pelo portal e ocorre o mesmo erro, em todas as 3 zonas de disponibilidade!

_Out of capacity for shape VM.Standard.A1.Flex in availability domain AD-2. Create the instance in a different availability domain or try again later. If you specified a fault domain, try creating the instance without specifying a fault domain, otherwise try creating the instance in a different availability domain. If that doesn’t work, please try again later._

**Comment by beandj** [comment]
> > Devido à utilização inicial das instâncias "VM.Standard.E3.Flex" para o laboratório, que são instâncias pagas, e só conseguimos acesso gratuito graças ao apoio da Oracle Cloud, estamos atualizando o cluster para utilizar as instâncias Always Free "VM.Standard.A1.Flex".
> > Se você possuir créditos e quiser continuar utilizando as instâncias "VM.Standard.E3.Flex", não há problema algum. No entanto, lembre-se de migrar antes do término dos créditos para evitar qualquer cobrança.
> > Além disso, nos próximos dias, planejamos migrar o cluster de OKE para um cluster não gerenciado. Essa mudança proporcionará maior liberdade e nos permitirá explorar mais ferramentas de estudo, mantendo a conformidade com a proposta do Always Free.
> > Todo o processo de migração estará disponível neste repositório e será feito da forma mais simples possível.
> 
> Salve Rafa, acabei de clonar o repo, o terraform ta reclamando: **Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded.** │ Suggestion: Request a service limit increase for this resource Containerengine Cluster
> 
> Não é problema com seu código, tentei subir manualmente pelo portal e ocorre o mesmo erro, em todas as 3 zonas de disponibilidade!
> 
> _Out of capacity for shape VM.Standard.A1.Flex in availability domain AD-2. Create the instance in a different availability domain or try again later. If you specified a fault domain, try creating the instance without specifying a fault domain, otherwise try creating the instance in a different availability domain. If that doesn’t work, please try again later._

Não tem mais essa instancia free nessa região.

**Comment by cesar-arnold** [comment]
@Rapha-Borges
Bom dia! 
Durante a semana estava tentando e pensei que fosse algo particular comigo, agora lendo os "comments" hoje dos colegas...
já me desculpando o extenso do texto - compilado aqui com resumo de algumas tentativas seguindo o passo-a-passo:

A VM até é criada com sucesso, quando começa a instalação dos pacotes/serviços apresentam-se alguns impedimentos conforme segue:

1) VM.Standard.A1.Flex
Always Free-eligible
Virtual machine, 1 core OCPU, 6 GB memory, 1 Gbps network bandwidth
...
ao tentar criar reclama:
Out of capacity for shape VM.Standard.A1.Flex in availability domain AD-2. Create the instance in a different availability domain or try again later. If you specified a fault domain, try creating the instance without specifying a fault domain, otherwise try creating the instance in a different availability domain. If that doesn’t work, please try again later. [Learn more about host capacity.](https://www.oracle.com/cloud/free/faq.html)

OBS: 
- se usar VM.Standard.E2.1.Micro (Always Free-eligible) somente 1Gb RAM quando tento levantar os serviços - fica travando por pouca memória.
- se usar a imagem indicada por você: 
image_id = ocid1.image.oc1.iad.aaaaaaaanwsto6tqklfuawgqrve5ugjpbff3l5qtb7bs35dp72ewcnsuwoka é um CentOS..

(wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install terraform **lsb_release** não retorna o OS) 

Até ai tudo bem... foi instalado nesse CentOS mesmo, com YUM o terraform (com outros passos)- OK sem problemas....

- Depois do terraform instalado, e tentando executar **oci session authenticate --region us-ashburn-1**
reclama que a versão default do python 3.6.8 (com criptografia deprecada) não consegue executar o **oci session authenticate --region us-ashburn-1** - pede para terminar a execução em um browser, faço login e não conclui. 

Acertando versão do python/pip...
oci -v (retorna conforme abaixo)
3.37.4

Em seguida:
oci session authenticate --region us-ashburn-1

Open the following URL in a web browser window to continue:
Copy/paste da URL gerada, no Chrome, após autenticar na Cloud Oracle com as credenciais corretamente acaba sempre nesta mensagem:

http://localhost:8181/#id_token=eyJraWQiOiJhc3dfb2MxX2o0eGQiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX3R6IjoiQW1lcmljYVwvQ2hpY2FnbyIsInN1YiI6Im9jaWQxLnVzZXIub2MxLi5hYWFhYWFhYWpiN2lnZm95eTdxMm9wZmN5NnhhZmUzaXJyY2R3czJnb3l1NWFscTQzdW9heHFpdm52N2EiLCJ1c2VyX2xvY2FsZSI6ImVuIiwidGVuYW50X2hvbWVfcmVnaW9uIjoiSUFEIiwiYW1yIjoiW1VTRVJOQU1FX1BBU1NXT1JELCBUT1RQXSIsImlzcyI6ImF1dGhTZXJ2aWNlLm9yYWNsZS5jb20iLCJkb21haW5fc3RyaXBlX3VybCI6Imh0dHBzOlwvXC9pZGNzLWY0OWQ2ZWQ4OWE4ZjQ5NjlhMzE5MmMxMjNjNGQ1M2ZmLmlkZW50aXR5Lm9yYWNsZWNsb3VkLmNvbTo0NDMiLCJkb21haW5fbmFtZSI6IkRlZmF1bHQiLCJzY29wZSI6Im9wZW5pZCIsInVzZXJfbGFuZyI6ImVuIiwiZXhwIjoxNzA1NTkyMzQxLCJkb21haW5faG9tZV9yZWdpb24iOiJ1cy1hc2hidXJuLTEiLCJpYXQiOjE3MDU1ODg3NDEsImp0aSI6IjA5ODUzNTU1LTI0ZDEtNDg3Zi1iNTg2LWUzYzI5MzMxMzljNCIsInRlbmFudCI6Im9jaWQxLnRlbmFuY3kub2MxLi5hYWFhYWFhYW53Z3pvaWllZGw1dWw2cnQzanBkemJ1Z2hmaXJ6ZGpkaGJ2eDNrd2J1bTJhcHFxb3VwZ3EiLCJ0ZW5hbnRfbmFtZSI6ImNlc2FyYXJub2xkMjM5Iiwic3RfaGFzaCI6InlNZjZ1VFZvc05vV0ZsUWxBam1iIiwibm9uY2UiOiI5ZDFjYTRkMi02NGNkLTQyMDYtYjRlMi1lZjdlYzZlY2QzNjciLCJpc3N1ZXJfcmVnaW9uIjoiSUFEIiwiYXVkIjoiaWFhc19jb25zb2xlIiwidHR5cGUiOiJpZF90b2tlbiIsIm5hbWUiOiJjZXNhcmFybm9sZEBnbWFpbC5jb20iLCJyZWRpcmVjdF91cmkiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODE4MSIsInB1bHAiOiJPY2lDb25zb2xlIiwiZG9tYWluX29jaWQiOiJvY2lkMS5kb21haW4ub2MxLi5hYWFhYWFhYWU1ZHgza3A1Zmtsd2pzbDJxNWgyMndmNmYybWZ3dHcyZm11d3phcWo0dm9jZHVjNmg0bGEifQ.JlwidNZ7z2sqCoJijAPelQW82cJ4PhKbZMOpFQTCM4ANJ5isZE558PR0uGvWiqiaSNLQnNxFHZ4QeKjFbyCNaF2-_JK5eQfxU-9mTJHOeTNPxBj3mvA9KZ0qneuEdWU9oDhcmvntltW0zTbmsc1itReLoA6Ch8on93CbVCYzfv4nC_o4dmsVtgU8YSv6mVyHO2bAvEtmEU80ytYlgzHFvNoZxkiheq8k3nRpZpdfFHb_Q3_p2g0tP3L1nA8s0LFHJTo52MLE1XIyJnBc8QxsxzP6xn0HaY5tjC4v52B4A_tIlY1nZOe0nOy02cDzzBspm3Z7rnhDr0KEo00803yIlA&security_token=eyJraWQiOiJhc3dfb2MxX2o0eGQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFqYjdpZ2ZveXk3cTJvcGZjeTZ4YWZlM2lycmNkd3MyZ295dTVhbHE0M3VvYXhxaXZudjdhIiwibWZhX3ZlcmlmaWVkIjoidHJ1ZSIsImlzcyI6ImF1dGhTZXJ2aWNlLm9yYWNsZS5jb20iLCJwdHlwZSI6InVzZXIiLCJzZXNzX2V4cCI6IkZyaSwgMTkgSmFuIDIwMjQgMTQ6Mzk6MDEgVVRDIiwic2lkIjoiYmM2MTRhYzlmOWU4NDQ5ZGIwMWMxZjc1NmZlZGMzYjc6ZWQyYzk3IiwiYXVkIjoib2NpIiwicHN0eXBlIjoibmF0diIsInR0eXBlIjoibG9naW4iLCJleHAiOjE3MDU1OTIzNDEsImlhdCI6MTcwNTU4ODc0MSwianRpIjoiOWYzZWFmZDgtNmY4YS00ZDY5LTk5ZjktNzIxNGFiNTU0MmEwIiwidGVuYW50Ijoib2NpZDEudGVuYW5jeS5vYzEuLmFhYWFhYWFhbndnem9paWVkbDV1bDZydDNqcGR6YnVnaGZpcnpkamRoYnZ4M2t3YnVtMmFwcXFvdXBncSIsImp3ayI6IntcImt0eVwiOiBcIlJTQVwiLCBcIm5cIjogXCI0a24wdkNQVVFHMFJiV21iaUh3NmZtUXR5TXU3UHF6SmltMTA0elM0bkJzUkVQeVFTcHJGcjZuTnF4NERyeEo5Nm1hcHd2eHZvWFBEUHc3NzdETlh0SzFaZzdZcEFmZkEyc3Vub013YUJuek5lWG5GRHdEbWhmbVFzdWJ1ZkplMHFpQXNCQVN0ZWVybmVQSGlRbmc3cE9jd3Vvc2ExSWpsdXVHOEt0Z0FlWWhMSVhhY1J3UkFCY2NUWXRxcThGbkFRbDBEMGUxdW1FdDNFVDJDRkpLQnZ0TkEyY2VHRVpKdUhMcExHeTlpTWd1THljM18wZkxPNlJJWURXeUVVSVdVbEhyWjZacTFrX0pvTldjT1Z3V0ZZY1IxUVBTSVJJbDJKYjFld0h2Q1ZlY0t5ZS11N1ZfTk8tcTgtZG12a0pBSDlXYlo4OHEyR21IMG1OdzJQQjFIYXdcIiwgXCJlXCI6IFwiQVFBQlwiLCBcImtpZFwiOiBcIklnbm9yZWRcIn0ifQ.eojnzeCdn1vKcvku0y2HnvQI_ZRBEzyzeHb2JFRTMkdgUE9jy58VJ5YE7Kk36TYUOl3ip82JtmhFvofO8OgH0RXqNEpk5Ywp8khCnzDu5qkXIuSSIazEiEJjF4Jr0ub3kT3FxCmlZHkX3-Ca-O-SJ_ltA_ehmfhQ7ezZgxMSbg7YiSFZZR6qzuQ5tuNWt5NJBjHJg1DffzE119Rk-20n7gzgZEwCv0Ezjza7gkJkVqJ6FUYyjqK-cDNFvgwu8sVOpFt6zUHm8JTsAj3uWiYf59BHbFbmM_KWdOCS0vHko9et6s5f9oKGXVUmVv8gxQdEPQXkxGxqMvN7g68nQ7zhfw&token_type=Security&state=null

This site can’t be reached
localhost refused to connect.

Parando neste ponto aqui:
Configurando o OCI CLI
1. Execute o comando de configuração:
oci session authenticate --region us-ashburn-1

- Considerando que:
- a "VM.Standard.E3.Flex" (usado no exemplo , não ser a mais recomendada);
- a image indicada (image_id = ocid1.image.oc1.iad.aaaaaaaanwsto6tqklfuawgqrve5ugjpbff3l5qtb7bs35dp72ewcnsuwoka é um CentOS com python 3.6.8; 
- a Always Free "VM.Standard.A1.Flex" reclama "Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded." 

Há identificada alguma correção nesse roteiro para a instalação com sucesso de VM funcional na Cloud Oracle, por gentileza?

Perdoe o incômodo.
Grato pela compreensão.

**Comment by Rapha-Borges** [comment]
> Bom dia! Durante a semana estava tentando e pensei que fosse algo particular comigo, agora lendo os "comments" hoje dos colegas... já me desculpando o extenso do texto - compilado aqui com resumo de algumas tentativas seguindo o passo-a-passo:
> 
> A VM até é criada com sucesso, quando começa a instalação dos pacotes/serviços apresentam-se alguns impedimentos conforme segue:
> 
>     1. VM.Standard.A1.Flex
>        Always Free-eligible
>        Virtual machine, 1 core OCPU, 6 GB memory, 1 Gbps network bandwidth
>        ...
>        ao tentar criar reclama:
>        Out of capacity for shape VM.Standard.A1.Flex in availability domain AD-2. Create the instance in a different availability domain or try again later. If you specified a fault domain, try creating the instance without specifying a fault domain, otherwise try creating the instance in a different availability domain. If that doesn’t work, please try again later. [Learn more about host capacity.](https://www.oracle.com/cloud/free/faq.html)

Erro `Out of capacity` indica que a conta ou região não tem disponibilidade para a criação da instância com o shape escolhido `VM.Standard.A1.Flex`. Novas instâncias com esse shape podem (ou não) serem liberadas a qualquer momento.
> 
> 
> OBS:
> 
>     * se usar VM.Standard.E2.1.Micro (Always Free-eligible) somente 1Gb RAM quando tento levantar os serviços - fica travando por pouca memória.

O shape `VM.Standard.E2.1.Micro` não está na lista de shapes compatíveis com o OKE (Oracle Kubernetes Engine). Por esse motivo, não é possível criar um cluster OKE com esse shape.
> 
>     * se usar a imagem indicada por você:
>       image_id = ocid1.image.oc1.iad.aaaaaaaanwsto6tqklfuawgqrve5ugjpbff3l5qtb7bs35dp72ewcnsuwoka é um CentOS..

A imagem utilizada é o `Oracle-Linux-8.8-2023.09.26-0-OKE-1.28.2-653` para a região de `us-ashburn-1`. 

https://docs.oracle.com/en-us/iaas/images/image/9e988ba5-267c-44fc-bbe7-68936d6b344c/
> 
> 
> (wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list sudo apt update && sudo apt install terraform **lsb_release** não retorna o OS)
> 
> Até ai tudo bem... foi instalado nesse CentOS mesmo, com YUM o terraform (com outros passos)- OK sem problemas....

Sim, se você utiliza uma distribuição Linux diferente do Ubuntu, é necessário instalar o Terraform conforme o site oficial.

https://developer.hashicorp.com/terraform/install
> 
>     * Depois do terraform instalado, e tentando executar **oci session authenticate --region us-ashburn-1**
>       reclama que a versão default do python 3.6.8 (com criptografia deprecada) não consegue executar o **oci session authenticate --region us-ashburn-1** - pede para terminar a execução em um browser, faço login e não conclui.
> 
> 
> Acertando versão do python/pip... oci -v (retorna conforme abaixo) 3.37.4
> 
> Em seguida: oci session authenticate --region us-ashburn-1
> 
> Open the following URL in a web browser window to continue: Copy/paste da URL gerada, no Chrome, após autenticar na Cloud Oracle com as credenciais corretamente acaba sempre nesta mensagem:
> 
> http://localhost:8181/#id_token=eyJ...
> 
> This site can’t be reached localhost refused to connect.
> 
Se você se atentar ao link gerado, ele inicia com `http://localhost:8181` ao invés de um link válido da Oracle Cloud (https://login.[region].oraclecloud.com/). Possivelmente, algum erro gerado por configurações do seu navegador ou do sistema operacional. Aconselho refazer a instação do OCI CLI buscando seguir o passo a passo do tutorial oficial. 

Obs: Esse erro não é relacionado diretamente com o lab, mas sim com a instalação do OCI CLI.

https://docs.oracle.com/en-us/iaas/Content/API/Concepts/cliconcepts.htm#Requirements

https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/cliinstall.htm#InstallingCLI__linux_and_unix

https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/climanualinst.htm#Manual_Installation

> Parando neste ponto aqui: Configurando o OCI CLI
> 
>     1. Execute o comando de configuração:
>        oci session authenticate --region us-ashburn-1
> 
> 
>     * Considerando que:
> 
>     * a "VM.Standard.E3.Flex" (usado no exemplo , não ser a mais recomendada);

O shape `VM.Standard.E3.Flex` é a instância mais recomendada para o OKE (Oracle Kubernetes Engine) na região de `us-ashburn-1` no momento. Pois estamos utilizando os créditos oferecidos pela Oracle para o #MêsDoKubernetes. Já que o shape `VM.Standard.A1.Flex` aparentemente não está disponível para criação de novas instâncias, devido alta demanda.

>     * a image indicada (image_id = ocid1.image.oc1.iad.aaaaaaaanwsto6tqklfuawgqrve5ugjpbff3l5qtb7bs35dp72ewcnsuwoka é um CentOS com python 3.6.8;

Acredito que você está fazendo algum confusão, já que a imagem utilizada é o `Oracle-Linux-8.8-2023.09.26-0-OKE-1.28.2-653` para a região de `us-ashburn-1`. Provavelmente, CentOS é a distribuição Linux que você está utilizando na sua máquina local.
> 
>     * a Always Free "VM.Standard.A1.Flex" reclama "Error: 400-LimitExceeded, The cluster limit for this tenancy has been exceeded."
Atente-se as configurações especificas para cada `shape`. Sendo necessário atualizar o arquivo `variables.tf` com as configurações do `shape`, `image` e `region` que você deseja utilizar.
> 
> 
> Há identificada alguma correção nesse roteiro para a instalação com sucesso de VM funcional na Cloud Oracle, por gentileza?
> 
> Perdoe o incômodo. Grato pela compreensão.

**Comment by Rapha-Borges** [comment]
> # Nova branch para testes do cluster always-free
> 
> Criei a branch [always-free](https://github.com/Rapha-Borges/oke-free/tree/always-free) para testar o cluster utilizando apenas recursos gratuitos. No entanto, para realizar esse procedimento, você possivelmente precisará fazer o upgrade da conta para Pay As You Go para ter acesso à maior disponibilidade das instâncias VM.Standard.A1.Flex (único shape Always Free compatível com o OKE).
> 
> Fique atento ao utilizar o cluster dessa forma, pois outros recursos, não inclusos no Always Free, podem ser criados dependendo de como você utiliza a sua conta.
> 
> Por se tratar de um projeto colaborativo, mesmo que revisado por mim, não me responsabilizo por custos gerados devido à utilização desse laboratório. Sempre crie um alerta de custos no valor de R$ 1,00 para não ter surpresas.

## Adicionadas novas informações no comentário inicial.
